active_profile: Default
profiles:
    - name: Default
      server: localhost
      port: 8001
      language: es
      log_folders:
        - path: C:\Users\jjara\Desktop\proyectos\versaBOT\versaWYS\logs\orm.log
          extensions:
            - '*.log'
            - '*.txt'
          filters:
            - error
            - warning
          enabled: true
          format: json
        - path: C:\Users\jjara\Desktop\proyectos\versaBOT\versaWYS\logs
          extensions:
            - '*.log'
            - '*.txt'
          filters:
            - error
            - warning
            - debug
          enabled: true
          format: json
window_position:
    x: 5113
    "y": 0
    width: 654
    height: 1087
